### ISSUE TITLE
the app.js doesnt shows the latest

### ISSUE THREAD

**Issue by moshdev2213** [AcademiaY3/AFLab#4]
![image](https://github.com/AcademiaY3/AFLab/assets/103739510/45963dd3-136d-4f91-8498-56811c0a47e8)

**Comment by Dilshan09** [comment]
switch to main branch.

**Comment by IT21298912** [comment]
please check the branch

**Comment by moshdev2213** [comment]
all right it got it , i was not in the correct branch

**Comment by moshdev2213** [comment]
> please check the branch

got it
